#!/usr/bin/env bash
# basic-usage.sh — create a sample markdown post and draft it with the Blogizi CLI.
#
# Prerequisites:
#   npm install -g blogizi
#   blogizi auth YOUR_ACCOUNT_API_KEY
#   blogizi use your-project-slug   # if you have more than one project
#
# Usage:
#   ./examples/basic-usage.sh
#   PUBLISH=1 ./examples/basic-usage.sh   # also run blogizi publish (goes live)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${ROOT}/examples/.tmp"
SLUG="cli-basic-usage-demo"
POST_PATH="${OUT_DIR}/${SLUG}.md"

if ! command -v blogizi >/dev/null 2>&1; then
  echo "blogizi not found. Install with: npm install -g blogizi" >&2
  exit 1
fi

if [[ ! -f "${HOME}/.blogizi/config.json" ]]; then
  echo "Not authenticated. Run: blogizi auth YOUR_ACCOUNT_API_KEY" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"

TODAY="$(date -u +%Y-%m-%d)"

cat >"${POST_PATH}" <<EOF
---
title: "CLI basic usage demo"
description: "Sample post created by examples/basic-usage.sh"
keyword: "blogizi cli"
slug: "${SLUG}"
status: "draft"
date: "${TODAY}"
readingTime: 0
wordCount: 0
---

This post was generated by \`examples/basic-usage.sh\`.

Edit the markdown, then run \`blogizi draft\` again or \`blogizi publish\` when you want it live.
EOF

echo "Wrote ${POST_PATH}"
echo "Drafting…"
blogizi draft "${POST_PATH}"

if [[ "${PUBLISH:-0}" == "1" ]]; then
  echo "PUBLISH=1 set — publishing live…"
  blogizi publish "${POST_PATH}"
else
  echo "Draft saved. To publish later: blogizi publish ${POST_PATH}"
fi
